---
engine_version: 0.4.20
file_version: 2024-07-31 12:31:23.886169000 Z
resources:
- name: user
  preferences:
    columns:
    - access_type: hidden
      name: notifications
    - name: webpush_notify_on_event_expired
      display_name: webpush_notify_on_event_expired
      column_type: boolean
      access_type: read_write
      virtual: true
      format: {}
      validators: []
  updated_at: 2024-07-31 09:31:23.886169000 -03:00
configs:
- key: header.links
  value:
  - name: "⭐ Star on GitHub"
    path: https://github.com/motor-admin/motor-admin-rails
  updated_at: 2024-07-31 08:49:39.461731000 -03:00
queries: []
dashboards: []
forms: []
alerts: []
api_configs:
- id: 1
  name: origin
  url: "/"
  preferences: {}
  description: 
  updated_at: 2024-07-31 08:49:39.481225000 -03:00
