:concurrency: 10

:queues:
  - default
  - chatwoot_webhooks
  - evolution_api_webhooks
  - evolution_api_delete_instance

# TODO: Fix webhooks queue to FIFO order
# :limits:
#   chatwoot_webhooks: 1
